смотри, вот моя модель
export class Device extends Model<InferAttributes<Device>, InferCreationAttributes<Device>> {
  id: CreationOptional<number>;
  name: string;
  price: number;
  rating: CreationOptional<number>;
  img: string;
//   brandId:  CreationOptional<number>;
  getBasketDevice: HasManyAddAssociationMixin<BasketDevice, number>;
  getRating: HasManyAddAssociationMixin<Rating, number>;
  getDeviceInfo: HasManyAddAssociationMixin<DeviceInfo, number>;
  typeId: BelongsToCreateAssociationMixin<Type>;
  brandId: BelongsToCreateAssociationMixin<Brand>;
}

мой deviceController:
  getAll = catchErrors(async (req: Request<{}, {}, BaseDeviceInter>, res) => {
    const brandId = req.query.brandId as string;
    const typeId = req.query.typeId as string;
    let devices;
    if (!brandId && !typeId) {
      devices = await Device.findAll();
    }

    if (brandId && !typeId) {
      devices = await Device.findAll({ where: { brandId: Number(brandId) } }); // ошибка по типам
    }
})

Почему мне выбивает TS ошибку с типами, если я уже задал в модели ассоциацию belongsTo (Brand)

